name: set-uotput deprecated
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment to deploy to.
        required: true
        options:
          - Staging
          - Production
jobs:
  pre_build:
    name : Pre build
    runs-on: ubuntu-latest
    env:
      MAJOR: 1
      MINOR: 0
    outputs:
      version: ${{ steps.create_version.outputs.VERSION }}
    steps:
      - id: create_version
        run: |
          VERSION=${MAJOR}.${MINOR}.${{ github.run_number }}_${{ github.event.inputs.environment }}
          echo "$VERSION"
          # echo "::set-output name=VERSION::$VERSION"
          # This is the new form => github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

  test:
    name: Test set output
    runs-on: ubuntu-latest
    needs: pre_build
    steps:
    - name: Use Output
      run: |
        echo ${{ needs.pre_build.outputs.version }}