name: realese versions tests
on:
  release:
    types: [released]
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v2

    - name: Set VERSION variable from commit tag
      run:  |
        GITHUB_REFS=${{ github.ref }}
        echo "Versioning of package id from new tags"
        $VERSION_FROM_EVENT=$(echo ${{ github.event.release.tag_name }} | sed -e 's/^v//')
        $VERSION=$(echo "${{ github.ref }}" | sed -e 's#^refs/tags/v##')
        echo "VERSION_FROM_EVENT=$VERSION_FROM_EVENT" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Test
      run: |
       echo ${{ env.VERSION }}
       echo ${{ env.VERSION_FROM_EVENT }}
